use_frameworks!

target 'BeautyJSON_Example' do
  pod 'BeautyJSON', :path => '../'

  target 'BeautyJSON_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
